language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

script:
  - docker --version
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user yinkaenoch/udagram-api-user:v1
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed yinkaenoch/udagram-api-feed:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend yinkaenoch/udagram-frontend:v1
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy yinkaenoch/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yinkaenoch/reverseproxy:v1
  - docker push yinkaenoch/udagram-api-feed:v1
  - docker push yinkaenoch/udagram-api-user:v1
  - docker push yinkaenoch/udagram-frontend:v1
